# The name of the current part. The name will stand on the sidebar
name: Division

# Optional: The description of the part
description: Das ist der Test zur Division.

# Assets which will be cached if the user is offline. The assets need to be in the asset directory
assets: []

# The content of the part.
items:
- name: Quiz
  # Optional: Max time in seconds (here: 10 minutes)
  #time: 600
  type: quiz
  questions:
  - title: "Was ist die Division?"
    description: "Was ist die Division?"
    evaluation: "Man teilt Zahlen durch eine andere."
    answers:
    - name: "Man zÃ¤hlt Zahlen zusammen."
    - name: "Man zieht Zahlen voneinander ab."
    - name: "Man nimmt Zahlen so oft wie eine andere Zahl."
    - name: "Man teilt Zahlen durch eine andere."
      points: 5
      correct: true
  - title: "Wie ist die Division aufgebaut?"
    description: "Wie ist die Division aufgebaut?"
    evaluation: "Faktor*Faktor=Wert des Produkts"
    answers:
    - name: "Minuend-Subtrahend=Wert der Differenz"
    - name: "Faktor*Faktor=Wert des Produkts"
    - name: "Summand+Summand=Wert der Summe"
    - name: "Dividend/Divisor=Wert des Quotienten"
      points: 5
      correct: true
- name: "Ende"
  description: "Du hast es geschafft!"
  type: text
  text: >
    "Das war es leider auch von diesem Kurs. Mehr Inhalt ist geplant und kommt bald. Bis dahin!"